export * from './Home';
export * from './Login';
export * from './MyPerfil';
export * from './Register';
export * from './Restaurant';
export * from './ResultsFilter';
export * from './ReserveDone';
export * from './Tastes';
export * from './index';
