export const galleryCards = [
    {
        id : 1,
        title : 'Sabores del Riachuelo',
        subtitle : 'Inspirado en la rica historia y cultura de La Boca, este establecimiento ofrece una experiencia culinaria única que celebra los sabores auténticos y tradicionales de la región.',
        img : 'https://a.storyblok.com/f/53624/1365x1800/5f945a262a/two-men-on-a-colorful-balcony-in-caminito-la-boca-buenos-aires.jpg',
        distance: '22km',
        rating: '4.5',
        priceRange: '200 - 400',
        latitude: '-34.603722',
        longitude: '-58.381592',
        serviceActive: [0,2,3,4,5], 
        foodType: 'Parrilla Argentina. Churrasquería.',
        description: ['Almuerzo y cenas','Asientos al aire libre, wi-fi']
    },
    {
        id : 2,
        title : 'La Bohème',
        subtitle : 'Inspirado en la esencia artística y vanguardista de Montmartre en París, este bar ofrece una experiencia única para aquellos que buscan sumergirse en un ambiente acogedor y lleno de creatividad.',
        img : 'https://retractableawningsreviews.com/wp-content/uploads/2022/09/2022-09-16_09h21_05-770x1024.png',
        distance: '22km',
        rating: '4.5',
        priceRange: '200 - 400',
        latitude: '-34.603722',
        longitude: '-58.381592',
        serviceActive: [0,2,5],
        foodType: 'Restaurante de pastas',
        description: ['Cena','Estacionamiento']
    },
    {
        id : 3,
        title : 'La Perla de Caminito',
        subtitle : 'Inspirado en la esencia artística y vanguardista de Montmartre en París, este bar ofrece una experiencia única para aquellos que buscan sumergirse en un ambiente acogedor y lleno de creatividad.',
        img : 'https://cdn-italiani-media.italiani.it/site-misiones/sites/87/2020/06/bar-la-perla.jpg',
        distance: '22km',
        rating: '4.5',
        priceRange: '250 - 375',
        latitude: '-34.603722',
        longitude: '-58.381592',
        serviceActive: [0,2,5],
        foodType: 'Restaurante de pastas',
        description: ['Cena','Estacionamiento']
    },
    {
        id : 4,
        title : 'Latino Sandwich',
        subtitle : 'Inspirado en la esencia artística y vanguardista de Montmartre en París, este bar ofrece una experiencia única para aquellos que buscan sumergirse en un ambiente acogedor y lleno de creatividad.',
        img : 'https://images.unsplash.com/photo-1576541868107-41abf214751c?crop=faces%2Cedges&cs=tinysrgb&fit=crop&fm=jpg&ixid=M3wxMjA3fDB8MXxhbGx8fHx8fHx8fHwxNjg0MTU2MTUwfA&ixlib=rb-4.0.3&q=60&w=1200&auto=format&h=630&mark-w=64&mark-align=top%2Cleft&mark-pad=50&blend-mode=normal&blend-alpha=10&blend-w=1&mark=https%3A%2F%2Fimages.unsplash.com%2Fopengraph%2Flogo.png&blend=000000',
        distance: '22km',
        rating: '4.5',
        priceRange: '550 - 200',
        latitude: '-34.603722',
        longitude: '-58.381592',
        serviceActive: [0,2,5],
        foodType: 'Restaurante de pastas',
        description: ['Cena','Estacionamiento']
    },
    {
        id : 5,
        title : 'La Tranquera',
        subtitle : 'Inspirado en la esencia artística y vanguardista de Montmartre en París, este bar ofrece una experiencia única para aquellos que buscan sumergirse en un ambiente acogedor y lleno de creatividad.',
        img : 'https://media-cdn.tripadvisor.com/media/photo-s/07/45/3a/7c/la-tranquera.jpg',
        distance: '22km',
        rating: '4.5',
        priceRange: '200 - 400',
        latitude: '-34.603722',
        longitude: '-58.381592',
        serviceActive: [0,2,5],
        foodType: 'Restaurante de pastas',
        description: ['Cena','Estacionamiento']
    },
    {
        id : 6,
        title : 'Sabores del Riachuelo',
        subtitle : 'Inspirado en la rica historia y cultura de La Boca, este establecimiento ofrece una experiencia culinaria única que celebra los sabores auténticos y tradicionales de la región.',
        img : 'https://a.storyblok.com/f/53624/1365x1800/5f945a262a/two-men-on-a-colorful-balcony-in-caminito-la-boca-buenos-aires.jpg',
        distance: '22km',
        rating: '4.5',
        priceRange: '200 - 400',
        latitude: '-34.603722',
        longitude: '-58.381592',
        serviceActive: [0,2,5],
        foodType: 'Restaurante de pastas',
        description: ['Cena','Estacionamiento']
    },
    {
        id : 7,
        title : 'La Bohème',
        subtitle : 'Inspirado en la esencia artística y vanguardista de Montmartre en París, este bar ofrece una experiencia única para aquellos que buscan sumergirse en un ambiente acogedor y lleno de creatividad.',
        img : 'https://retractableawningsreviews.com/wp-content/uploads/2022/09/2022-09-16_09h21_05-770x1024.png',
        distance: '22km',
        rating: '4.5',
        priceRange: '200 - 400',
        latitude: '-34.603722',
        longitude: '-58.381592',
        serviceActive: [0,2,5],
        foodType: 'Restaurante de pastas',
        description: ['Cena','Estacionamiento']
    },
    {
        id : 8,
        title : 'La Perla de Caminito',
        subtitle : 'Inspirado en la esencia artística y vanguardista de Montmartre en París, este bar ofrece una experiencia única para aquellos que buscan sumergirse en un ambiente acogedor y lleno de creatividad.',
        img : 'https://cdn-italiani-media.italiani.it/site-misiones/sites/87/2020/06/bar-la-perla.jpg',
        distance: '22km',
        rating: '4.5',
        priceRange: '250 - 375',
        latitude: '-34.603722',
        longitude: '-58.381592',
        serviceActive: [0,2,5],
        foodType: 'Restaurante de pastas',
        description: ['Cena','Estacionamiento']
    },
    {
        id : 9,
        title : 'Latino Sandwich',
        subtitle : 'Inspirado en la esencia artística y vanguardista de Montmartre en París, este bar ofrece una experiencia única para aquellos que buscan sumergirse en un ambiente acogedor y lleno de creatividad.',
        img : 'https://images.unsplash.com/photo-1576541868107-41abf214751c?crop=faces%2Cedges&cs=tinysrgb&fit=crop&fm=jpg&ixid=M3wxMjA3fDB8MXxhbGx8fHx8fHx8fHwxNjg0MTU2MTUwfA&ixlib=rb-4.0.3&q=60&w=1200&auto=format&h=630&mark-w=64&mark-align=top%2Cleft&mark-pad=50&blend-mode=normal&blend-alpha=10&blend-w=1&mark=https%3A%2F%2Fimages.unsplash.com%2Fopengraph%2Flogo.png&blend=000000',
        distance: '22km',
        rating: '4.5',
        priceRange: '550 - 200',
        latitude: '-34.603722',
        longitude: '-58.381592',
        serviceActive: [0,2,5],
        foodType: 'Restaurante de pastas',
        description: ['Cena','Estacionamiento']
    },
    {
        id : 10,
        title : 'La Tranquera',
        subtitle : 'Inspirado en la esencia artística y vanguardista de Montmartre en París, este bar ofrece una experiencia única para aquellos que buscan sumergirse en un ambiente acogedor y lleno de creatividad.',
        img : 'https://retractableawningsreviews.com/wp-content/uploads/2022/09/2022-09-16_09h21_05-770x1024.png',
        distance: '22km',
        rating: '4.5',
        priceRange: '200 - 400',
        latitude: '-34.603722',
        longitude: '-58.381592',
        serviceActive: [0,2,5],
        foodType: 'Restaurante de pastas',
        description: ['Cena','Estacionamiento']
    },
    {
        id : 11,
        title : 'La Bohème',
        subtitle : 'Inspirado en la esencia artística y vanguardista de Montmartre en París, este bar ofrece una experiencia única para aquellos que buscan sumergirse en un ambiente acogedor y lleno de creatividad.',
        img : 'https://retractableawningsreviews.com/wp-content/uploads/2022/09/2022-09-16_09h21_05-770x1024.png',
        distance: '22km',
        rating: '4.5',
        priceRange: '200 - 400',
        latitude: '-34.603722',
        longitude: '-58.381592',
        serviceActive: [0,2,5],
        foodType: 'Restaurante de pastas',
        description: ['Cena','Estacionamiento']
    },
    {
        id : 12,
        title : 'La Bohème',
        subtitle : 'Inspirado en la esencia artística y vanguardista de Montmartre en París, este bar ofrece una experiencia única para aquellos que buscan sumergirse en un ambiente acogedor y lleno de creatividad.',
        img : 'https://retractableawningsreviews.com/wp-content/uploads/2022/09/2022-09-16_09h21_05-770x1024.png',
        distance: '22km',
        rating: '4.5',
        priceRange: '200 - 400',
        latitude: '-34.603722',
        longitude: '-58.381592',
        serviceActive: [0,2,5],
        foodType: 'Restaurante de pastas',
        description: ['Cena','Estacionamiento']
    }
]